# Generated by Django 4.2.19 on 2025-02-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eligibility', models.TextField()),
                ('documents', models.TextField()),
                ('offline_support', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
